-- ═══════════════════════════════════════════════════════════════
--  Polyculy H2 Schema (MODE=MSSQLServer)
-- ═══════════════════════════════════════════════════════════════

-- Drop tables in reverse dependency order
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS notification_preferences;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS informational_emails;
DROP TABLE IF EXISTS proposals;
DROP TABLE IF EXISTS shared_event_participants;
DROP TABLE IF EXISTS shared_events;
DROP TABLE IF EXISTS personal_event_visibility;
DROP TABLE IF EXISTS personal_events;
DROP TABLE IF EXISTS connection_display_preferences;
DROP TABLE IF EXISTS connections;
DROP TABLE IF EXISTS licences;
DROP TABLE IF EXISTS users;

-- Users
CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    avatar_url VARCHAR(500),
    timezone_id VARCHAR(50) DEFAULT 'America/New_York',
    calendar_created BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Licences
CREATE TABLE licences (
    licence_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    licence_code VARCHAR(50) NOT NULL UNIQUE,
    licence_type VARCHAR(20) NOT NULL DEFAULT 'alpha',
    pack_id INT,
    owner_user_id INT,
    gifted_to_email VARCHAR(255),
    gifted_by_user_id INT,
    redeemed_by_user_id INT,
    status VARCHAR(20) NOT NULL DEFAULT 'available',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    redeemed_at TIMESTAMP,
    CONSTRAINT fk_licence_owner FOREIGN KEY (owner_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_licence_gifted_by FOREIGN KEY (gifted_by_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_licence_redeemed_by FOREIGN KEY (redeemed_by_user_id) REFERENCES users(user_id)
);

-- Connections
CREATE TABLE connections (
    connection_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id_1 INT NOT NULL,
    user_id_2 INT,
    status VARCHAR(40) NOT NULL DEFAULT 'awaiting_signup',
    invited_email VARCHAR(255),
    invited_display_name VARCHAR(100),
    initiated_by INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_conn_user1 FOREIGN KEY (user_id_1) REFERENCES users(user_id),
    CONSTRAINT fk_conn_user2 FOREIGN KEY (user_id_2) REFERENCES users(user_id),
    CONSTRAINT fk_conn_initiated FOREIGN KEY (initiated_by) REFERENCES users(user_id)
);

-- Connection Display Preferences
CREATE TABLE connection_display_preferences (
    pref_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    target_user_id INT NOT NULL,
    nickname VARCHAR(100),
    avatar_override VARCHAR(500),
    calendar_color VARCHAR(7) DEFAULT '#7C3AED',
    CONSTRAINT fk_cdp_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_cdp_target FOREIGN KEY (target_user_id) REFERENCES users(user_id)
);

-- Personal Events
CREATE TABLE personal_events (
    event_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id INT NOT NULL,
    title VARCHAR(300) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    all_day BOOLEAN DEFAULT FALSE,
    timezone_id VARCHAR(50) DEFAULT 'America/New_York',
    event_details CLOB,
    address VARCHAR(500),
    reminder_minutes INT,
    visibility_tier VARCHAR(20) NOT NULL DEFAULT 'invisible',
    is_cancelled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pe_owner FOREIGN KEY (owner_user_id) REFERENCES users(user_id)
);

-- Personal Event Visibility
CREATE TABLE personal_event_visibility (
    visibility_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INT NOT NULL,
    target_user_id INT NOT NULL,
    visibility_type VARCHAR(20) NOT NULL DEFAULT 'busy_block',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pev_event FOREIGN KEY (event_id) REFERENCES personal_events(event_id) ON DELETE CASCADE,
    CONSTRAINT fk_pev_target FOREIGN KEY (target_user_id) REFERENCES users(user_id)
);

-- Shared Events
CREATE TABLE shared_events (
    shared_event_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_user_id INT NOT NULL,
    title VARCHAR(300) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    all_day BOOLEAN DEFAULT FALSE,
    timezone_id VARCHAR(50) DEFAULT 'America/New_York',
    event_details CLOB,
    address VARCHAR(500),
    reminder_minutes INT,
    reminder_scope VARCHAR(10) DEFAULT 'me',
    participant_visibility VARCHAR(20) DEFAULT 'visible',
    global_state VARCHAR(20) NOT NULL DEFAULT 'tentative',
    cancellation_reason VARCHAR(500),
    ownership_transfer_active BOOLEAN DEFAULT FALSE,
    ownership_transfer_deadline TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_se_organizer FOREIGN KEY (organizer_user_id) REFERENCES users(user_id)
);

-- Shared Event Participants
CREATE TABLE shared_event_participants (
    participant_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shared_event_id INT NOT NULL,
    user_id INT NOT NULL,
    attendance_type VARCHAR(20) NOT NULL DEFAULT 'required',
    response_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    is_one_hop BOOLEAN DEFAULT FALSE,
    link_person_user_id INT,
    one_hop_consent_given BOOLEAN DEFAULT FALSE,
    one_hop_activated BOOLEAN DEFAULT FALSE,
    is_removed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sep_event FOREIGN KEY (shared_event_id) REFERENCES shared_events(shared_event_id) ON DELETE CASCADE,
    CONSTRAINT fk_sep_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_sep_link FOREIGN KEY (link_person_user_id) REFERENCES users(user_id)
);

-- Proposals
CREATE TABLE proposals (
    proposal_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shared_event_id INT NOT NULL,
    proposer_user_id INT NOT NULL,
    proposed_start TIMESTAMP NOT NULL,
    proposed_end TIMESTAMP NOT NULL,
    message CLOB,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prop_event FOREIGN KEY (shared_event_id) REFERENCES shared_events(shared_event_id) ON DELETE CASCADE,
    CONSTRAINT fk_prop_user FOREIGN KEY (proposer_user_id) REFERENCES users(user_id)
);

-- Notifications
CREATE TABLE notifications (
    notification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    title VARCHAR(300) NOT NULL,
    message CLOB,
    related_entity_type VARCHAR(30),
    related_entity_id INT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Notification Preferences
CREATE TABLE notification_preferences (
    pref_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    is_enabled BOOLEAN DEFAULT TRUE,
    delivery_mode VARCHAR(20) DEFAULT 'instant',
    quiet_hours_start TIME,
    quiet_hours_end TIME,
    CONSTRAINT fk_np_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Audit Log
CREATE TABLE audit_log (
    audit_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id INT NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    entity_type VARCHAR(30) NOT NULL,
    entity_id INT NOT NULL,
    details CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(user_id)
);

-- Informational Emails
CREATE TABLE informational_emails (
    info_email_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shared_event_id INT NOT NULL,
    sender_user_id INT NOT NULL,
    recipient_email VARCHAR(255) NOT NULL,
    recipient_name VARCHAR(100),
    message_note CLOB,
    is_claimed BOOLEAN DEFAULT FALSE,
    claimed_by_user_id INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ie_event FOREIGN KEY (shared_event_id) REFERENCES shared_events(shared_event_id),
    CONSTRAINT fk_ie_sender FOREIGN KEY (sender_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_ie_claimer FOREIGN KEY (claimed_by_user_id) REFERENCES users(user_id)
);

-- Indexes
CREATE INDEX IX_connections_user1 ON connections(user_id_1);
CREATE INDEX IX_connections_user2 ON connections(user_id_2);
CREATE INDEX IX_connections_status ON connections(status);
CREATE INDEX IX_pe_owner ON personal_events(owner_user_id);
CREATE INDEX IX_pev_event ON personal_event_visibility(event_id);
CREATE INDEX IX_se_organizer ON shared_events(organizer_user_id);
CREATE INDEX IX_sep_event ON shared_event_participants(shared_event_id);
CREATE INDEX IX_sep_user ON shared_event_participants(user_id);
CREATE INDEX IX_notif_user ON notifications(user_id);
CREATE INDEX IX_notif_read ON notifications(is_read);
CREATE INDEX IX_audit_entity ON audit_log(entity_type, entity_id);
CREATE INDEX IX_audit_date ON audit_log(created_at DESC);
CREATE INDEX IX_licences_code ON licences(licence_code);
CREATE INDEX IX_licences_status ON licences(status);
